### ISSUE TITLE
Design layout/solder MURI DataLogger board

### ISSUE THREAD

**Issue by gailtsufc46** [MNSGC-Ballooning/MURI_Electrical#1]
Use one of the long solderable breadboards to create a new MURI daughterboard. I trimmed some of the fat (got rid of the accelerometer and pressure sensor, then I added the altimeter and decoupling capacitors to filter out noise on the power lines). We have one MS5607 on one of the other MURI payloads. Until we get more, this one will go on the datalogger payload. Email me if you need the data sheets for anything.

**Comment by asifally** [comment]
I made the three latching relays. We need some female headers to get started on the board. If anyone could grab some, that would be nice.

**Comment by gailtsufc46** [comment]
Hey guys, just to clarify, the schematic you want is under MURI_Electrical -> MURIrev2 -> MURI_MEGA_Datalogger.sch
